# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: auth.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'auth.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nauth.proto\x12\x04\x61uth\"6\n\x13ValidateUserRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"B\n\x14ValidateUserResponse\x12\x10\n\x08is_valid\x18\x01 \x01(\x08\x12\x18\n\x04user\x18\x02 \x01(\x0b\x32\n.auth.User\"/\n\x0cLoginRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"?\n\rLoginResponse\x12\x14\n\x0c\x61\x63\x63\x65ss_token\x18\x01 \x01(\t\x12\x18\n\x04user\x18\x02 \x01(\x0b\x32\n.auth.User\"Y\n\x0fRegisterRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\x12\x11\n\tfull_name\x18\x03 \x01(\t\x12\x12\n\navatar_url\x18\x04 \x01(\t\"H\n\x04User\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x11\n\tfull_name\x18\x03 \x01(\t\x12\x12\n\navatar_url\x18\x04 \x01(\t2\xbe\x01\n\x0b\x41uthService\x12\x45\n\x0cValidateUser\x12\x19.auth.ValidateUserRequest\x1a\x1a.auth.ValidateUserResponse\x12\x30\n\x05Login\x12\x12.auth.LoginRequest\x1a\x13.auth.LoginResponse\x12\x36\n\x08Register\x12\x15.auth.RegisterRequest\x1a\x13.auth.LoginResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VALIDATEUSERREQUEST']._serialized_start=20
  _globals['_VALIDATEUSERREQUEST']._serialized_end=74
  _globals['_VALIDATEUSERRESPONSE']._serialized_start=76
  _globals['_VALIDATEUSERRESPONSE']._serialized_end=142
  _globals['_LOGINREQUEST']._serialized_start=144
  _globals['_LOGINREQUEST']._serialized_end=191
  _globals['_LOGINRESPONSE']._serialized_start=193
  _globals['_LOGINRESPONSE']._serialized_end=256
  _globals['_REGISTERREQUEST']._serialized_start=258
  _globals['_REGISTERREQUEST']._serialized_end=347
  _globals['_USER']._serialized_start=349
  _globals['_USER']._serialized_end=421
  _globals['_AUTHSERVICE']._serialized_start=424
  _globals['_AUTHSERVICE']._serialized_end=614
# @@protoc_insertion_point(module_scope)
