# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: task.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'task.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntask.proto\x12\x05tasks\"M\n\rUpdateTaskReq\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x11\n\ttask_name\x18\x02 \x01(\t\x12\x18\n\x10task_description\x18\x03 \x01(\t\"M\n\rUpdateTaskRes\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x11\n\ttask_name\x18\x02 \x01(\t\x12\x18\n\x10task_description\x18\x03 \x01(\t\"D\n\x04Task\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x11\n\ttask_name\x18\x02 \x01(\t\x12\x18\n\x10task_description\x18\x03 \x01(\t\"\x1d\n\nGetTaskReq\x12\x0f\n\x07task_id\x18\x01 \x01(\t\"\'\n\nGetTaskRes\x12\x19\n\x04task\x18\x01 \x01(\x0b\x32\x0b.tasks.Task\"\r\n\x0bGetTasksReq\")\n\x0bGetTasksRes\x12\x1a\n\x05tasks\x18\x01 \x03(\x0b\x32\x0b.tasks.Task\"@\n\x11\x43reateTaskRequest\x12\x11\n\ttask_name\x18\x01 \x01(\t\x12\x18\n\x10task_description\x18\x02 \x01(\t\"R\n\x12\x43reateTaskResponse\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x11\n\ttask_name\x18\x02 \x01(\t\x12\x18\n\x10task_description\x18\x03 \x01(\t\" \n\rDeleteTaskReq\x12\x0f\n\x07task_id\x18\x01 \x01(\t\"*\n\rDeleteTaskRes\x12\x19\n\x04task\x18\x01 \x01(\x0b\x32\x0b.tasks.Task2\xaa\x02\n\x0cTasksService\x12\x41\n\nCreateTask\x12\x18.tasks.CreateTaskRequest\x1a\x19.tasks.CreateTaskResponse\x12\x38\n\nUpdateTask\x12\x14.tasks.UpdateTaskReq\x1a\x14.tasks.UpdateTaskRes\x12\x32\n\x08GetTasks\x12\x12.tasks.GetTasksReq\x1a\x12.tasks.GetTasksRes\x12\x38\n\nDeleteTask\x12\x14.tasks.DeleteTaskReq\x1a\x14.tasks.DeleteTaskRes\x12/\n\x07GetTask\x12\x11.tasks.GetTaskReq\x1a\x11.tasks.GetTaskResb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'task_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_UPDATETASKREQ']._serialized_start=21
  _globals['_UPDATETASKREQ']._serialized_end=98
  _globals['_UPDATETASKRES']._serialized_start=100
  _globals['_UPDATETASKRES']._serialized_end=177
  _globals['_TASK']._serialized_start=179
  _globals['_TASK']._serialized_end=247
  _globals['_GETTASKREQ']._serialized_start=249
  _globals['_GETTASKREQ']._serialized_end=278
  _globals['_GETTASKRES']._serialized_start=280
  _globals['_GETTASKRES']._serialized_end=319
  _globals['_GETTASKSREQ']._serialized_start=321
  _globals['_GETTASKSREQ']._serialized_end=334
  _globals['_GETTASKSRES']._serialized_start=336
  _globals['_GETTASKSRES']._serialized_end=377
  _globals['_CREATETASKREQUEST']._serialized_start=379
  _globals['_CREATETASKREQUEST']._serialized_end=443
  _globals['_CREATETASKRESPONSE']._serialized_start=445
  _globals['_CREATETASKRESPONSE']._serialized_end=527
  _globals['_DELETETASKREQ']._serialized_start=529
  _globals['_DELETETASKREQ']._serialized_end=561
  _globals['_DELETETASKRES']._serialized_start=563
  _globals['_DELETETASKRES']._serialized_end=605
  _globals['_TASKSSERVICE']._serialized_start=608
  _globals['_TASKSSERVICE']._serialized_end=906
# @@protoc_insertion_point(module_scope)
